language: node_js
node_js:
  - "node"

sudo: required

branches:
  only:
  - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn global add firebase-tools@latest
script:
- ng build --prod
- firebase use --token $FIREBASE_TOKEN ng-playground-diogen737
- firebase deploy -m "build $TRAVIS_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
cache:
  yarn: true
  directories:
  - "node_modules"