language: node_js
node_js:
  - "node"

before_script:
- npm i -g firebase-tools
script:
- npm run build
- firebase use --token $FIREBASE_TOKEN angular-playground
- firebase deploy -m "build $TRAVIS_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
cache:
  directories:
  - "node_modules"