language: node_js
node_js:
  - "node"

build:
  only:
  - master
before_script:
- yarn global add firebase-tools
script:
- ng build --prod
- firebase use --token $FIREBASE_TOKEN ng-playground-diogen737
- firebase deploy -m "build $TRAVIS_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
cache:
  directories:
  - "node_modules"